version: "3.9"

services:
  app:
    build: .
    container_name: mybiat_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mybiat
      - PORT=3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
